### ISSUE TITLE
Bad direction left/right panes

### ISSUE THREAD

**Issue by isyara** [markalfred/sublime-pane-resizer#3]
Hi,

When i override keymaps (because not possible via  PluginName > Key binding User)

  { "keys": ["alt+right"], "command": "resize_pane", "args": {"direction": "out" }},
  { "keys": ["alt+left"], "command": "resize_pane", "args": {"direction": "in" }}

i have two panes :
- pane 1 : shorcuts works !
- pane 2 : shorcuts are inverted (direction)

**Comment by markalfred** [comment]
Hi @isyara,

The keys used are `+` and `-` because they **grow** and **shrink** the active pane. With your setup, pressing `alt+right` should always make your current pane bigger. So if you have the right pane selected, this may seem backwards. This is why `+` and `-` were used in the default configuration, rather than arrow keys.

If you'd like to use arrow keys, it may be more appropriate to use a setup like this:

```
{ "keys": ["alt+up"], "command": "resize_pane", "args": {"direction": "out" }},
{ "keys": ["alt+down"], "command": "resize_pane", "args": {"direction": "in" }}
```

Does this address your issue?

**Comment by isyara** [comment]
Ok ,

Thanks  !
